version: '3.8'

services:
  db:
    image: postgres:15
    container_name: devnotes_postgres
    restart: always
    environment:
      POSTGRES_USER: admin  
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: devnotes_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
